# -*- coding: utf-8 -*-
"""ClassImbalance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d148OZPXVuKggXaisP-jsccA1YdJyJ4p
"""

import numpy as np
import pandas as pd
import sklearn
import scipy
import matplotlib.pyplot as plt
!pip install -U imbalanced-learn

dataset = pd.read_csv('drive/MyDrive/ML_Data/creditcard.csv')
print(dataset.head())

X = dataset.iloc[:,1:30].values
y = dataset.iloc[:,30].values

print("Total no. of instances", len(y))
print("No. of zero class intances", sum(y==0))
print("No. of one class instances", sum(y==1))

#Random Oversampler
from imblearn.over_sampling import RandomOverSampler
obj = RandomOverSampler()
X_new, y_new = obj.fit_resample(X, y)
print("Total no. of instances", len(y_new))
print("No. of zero class intances", sum(y_new==0))
print("No. of one class instances", sum(y_new==1))

#Synthetic Generation of new data using SMOTE and ADASYN

from imblearn.over_sampling import SMOTE, ADASYN
obj = SMOTE()
X_new, y_new = obj.fit_resample(X, y)
print("Total no. of instances", len(y_new))
print("No. of zero class intances", sum(y_new==0))
print("No. of one class instances", sum(y_new==1))

obj = ADASYN()
X_new, y_new = obj.fit_resample(X, y)
print("Total no. of instances", len(y_new))
print("No. of zero class intances", sum(y_new==0))
print("No. of one class instances", sum(y_new==1))

#Random Undersampler
from imblearn.under_sampling import RandomUnderSampler
obj = RandomUnderSampler()
X_new, y_new = obj.fit_resample(X, y)
print("Total no. of instances", len(y_new))
print("No. of zero class intances", sum(y_new==0))
print("No. of one class instances", sum(y_new==1))