# -*- coding: utf-8 -*-
"""DataPrep.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aWYYgkVVLHiCLM5Gg10bTJ9u2RScnwb8
"""

#Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Loading the dataset
dataset = pd.read_csv('drive/MyDrive/ML_Data/loans.csv')
#print(dataset)

#Extracting the independent and dependent variables
X = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

#Dealing with Categorical columns
#Removing the extra dummy variable
X = pd.get_dummies(X, columns=['City'],drop_first= True)

#Encoding the dependent class variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

#print(y)

#Converting to numpy array
X = np.array(X)
y = np.array(y)

#print(X)
#print(y)

#Splitting the data into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#Dealing with Missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
X_train[:, [0,1]] = imputer.fit_transform(X_train[:,[0,1]])
X_test[:, [0,1]] = imputer.transform(X_test[:,[0,1]])

#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)