# -*- coding: utf-8 -*-
"""DecisionTreeReg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1stVuw5qs2gwgpMzoBu7TjWKf-oefhyK_
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Loading the dataset
dataset = pd.read_csv('drive/MyDrive/ML_Data/salary.csv')

#Extracting the independent and dependent variables
X = dataset.iloc[:,1:2]
y = dataset.iloc[:,-1]

#Converting to numpy array
X = np.array(X)
y = np.array(y)

#Splitting the data into training and testing set
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#Feature Scaling
#from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()
#X_train = scaler.fit_transform(X_train)
#X_test = scaler.transform(X_test)

#Create and Fit a Regressor Object
from sklearn.tree import DecisionTreeRegressor
regObj = DecisionTreeRegressor()
regObj.fit(X,y) 

#Visualizing Results of Polynomial Regression
plt.scatter(X, y, color='red')
plt.plot(X, regObj.predict(X), color='blue')
plt.title('Results')
plt.xlabel('Level')
plt.ylabel('Salary')
plt.show()

#Predicting with the Model 
print('Model Prediction:',regObj.predict([[8.33]]))

#Visualizing the Decision Tree Regression in higher resolution
X_grid = np.arange(min(X), max(X), 0.01)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, y, color = 'red')
plt.plot(X_grid, regObj.predict(X_grid), color = 'blue')
plt.title('Results')
plt.xlabel('Level')
plt.ylabel('Salary')
plt.show()