# -*- coding: utf-8 -*-
"""MultipleLR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-TMJDSqxP-5_c_0VnvvdZzonPjv2pCOp
"""

from math import sqrt
#Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Loading the dataset
dataset = pd.read_csv('drive/MyDrive/ML_Data/employee.csv')
#print(dataset)

#Extracting the independent and dependent variables
X = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

#print(X)
#print(y)

#Dealing with Categorical columns
#Removing the extra dummy variable
X = pd.get_dummies(X, columns=['Department'],drop_first= True)

print(X)

#Encoding the dependent class variable
#from sklearn.preprocessing import LabelEncoder
#le = LabelEncoder()
#y = le.fit_transform(y)

#Converting to numpy array
X = np.array(X)
y = np.array(y)


#Splitting the data into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)


#Dealing with Missing values
#from sklearn.impute import SimpleImputer
#imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
#X_train[:, [0,1]] = imputer.fit_transform(X_train[:,[0,1]])
#X_test[:, [0,1]] = imputer.transform(X_test[:,[0,1]])


#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#Fitting Multiple Linear Regression to Training Set
from sklearn.linear_model import LinearRegression
mlrObj = LinearRegression()
mlrObj.fit(X_train,y_train)

#Predicting on the Test Set
y_pred = mlrObj.predict(X_test)

#Backward Elimination
import statsmodels.api as sm
X = np.append(arr=np.ones((30,1)), values=X, axis=1)

# Convert to a float64
X = X.astype('float64')  # Without this, OLS function errors out

print(X[0:5,:])

X_sig = X[:,[0,1,2,3,4,5]]
obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

X_sig = X[:,[0,1,2,3,4]]
obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

X_sig = X[:,[0,1,3,4]]
obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

X_sig = X[:,[0,1,3]]
obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

X_sig = X[:,[0,3]]
obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

#Retaining only years of experience column
X_train_sig = X_train[:,2:3]
X_test_sig = X_test[:,2:3]

#Building a model with significant predictor
mlrObj_sig = LinearRegression()
mlrObj_sig.fit(X_train_sig, y_train)
y_sig_pred = mlrObj_sig.predict(X_test_sig)

#Calculating MSE and RMSE with all features
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print('mean squared error', mse)
print('root mean squared error', sqrt(mse))

#Calculating MSE and RMSE with only significant predictors
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_sig_pred)
print('mean squared error', mse)
print('root mean squared error', sqrt(mse))