# -*- coding: utf-8 -*-
"""PolynomialLR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J2mpl8m9DeV_0irnYJTM8yq8OHKYDwEm
"""

#Polynomial Regression
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Loading the dataset
dataset = pd.read_csv('drive/MyDrive/ML_Data/salary.csv')

#Extracting the independent and dependent variables
X = dataset.iloc[:,1:2]
y = dataset.iloc[:,-1]

#Converting to numpy array
X = np.array(X)
y = np.array(y)

#Splitting the data into training and testing set
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#Feature Scaling
#from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()
#X_train = scaler.fit_transform(X_train)
#X_test = scaler.transform(X_test)

#Fitting Linear Regression
from sklearn.linear_model import LinearRegression
lrObj = LinearRegression()
lrObj.fit(X, y)

#Polynomial Regression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
polyFeatureObj = PolynomialFeatures(degree=4)
X_poly = polyFeatureObj.fit_transform(X)
X_poly = X_poly[:,1:] #dropping the intercept column as that will be added by sklearn
prObj = LinearRegression()
prObj.fit(X_poly, y)

#Visualizing Results of Linear Regression
plt.scatter(X, y, color='red')
plt.plot(X, lrObj.predict(X), color='blue')
plt.title('Results of Linear Regression Model')
plt.xlabel('Level')
plt.ylabel('Salary')
plt.show()

#Visualizing Results of Polynomial Regression
plt.scatter(X, y, color='red')
plt.plot(X, prObj.predict(X_poly), color='blue')
plt.title('Results of Polynomial Regression Model')
plt.xlabel('Level')
plt.ylabel('Salary')
plt.show()

#Predicting with Linear Model
print('Linear Model Prediction: ', lrObj.predict([[8.33]]))

#Predicting with Polynomial Model
v = polyFeatureObj.fit_transform( [[8.33]] ) 
v = v[:,1:]
print('Polynomial Model Prediction:', prObj.predict(v))