# -*- coding: utf-8 -*-
"""RegularizedRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10yNIL_BdZmsvu-xbUDibNYXt-L5-Ncvp
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('drive/MyDrive/ML_Data/salary2.csv')

X = dataset.iloc[:,1:2].values
y = dataset.iloc[:,2].values

#Lets have a look at the data
plt.scatter(X, y, color='red')
plt.title('Visual Exploration of the data')
plt.xlabel('Level')
plt.ylabel('Salary')
plt.show()

#Polynomial Regression with No Regularization
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
polyFeatureObj = PolynomialFeatures(degree=10)
X_poly = polyFeatureObj.fit_transform(X)
prObj = LinearRegression()
prObj.fit(X_poly, y)

#Visualizing Results of Polynomial Regression
plt.scatter(X, y, color='red')
plt.plot(X, prObj.predict(X_poly), color='blue')
plt.title('Results of Polynomial Regression Model')
plt.xlabel('Level')
plt.ylabel('Salary')
plt.show()

#Polynomial Regression with Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge
polyFeatureObj = PolynomialFeatures(degree=10)
X_poly = polyFeatureObj.fit_transform(X)
ridgeObj = Ridge()
ridgeObj.fit(X_poly, y)

#Visualizing Results of Ridge Regression
plt.scatter(X, y, color='red')
plt.plot(X, ridgeObj.predict(X_poly), color='blue')
plt.title('Results of Ridge Regression Model')
plt.xlabel('Level')
plt.ylabel('Salary')
plt.show()

#Polynomial Regression with Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Lasso
polyFeatureObj = PolynomialFeatures(degree=10)
X_poly = polyFeatureObj.fit_transform(X)
lassoObj = Lasso()
lassoObj.fit(X_poly, y)

#Visualizing Results of Lasso Regression
plt.scatter(X, y, color='red')
plt.plot(X, lassoObj.predict(X_poly), color='blue')
plt.title('Results of Lasso Regression Model')
plt.xlabel('Level')
plt.ylabel('Salary')
plt.show()