# -*- coding: utf-8 -*-
"""SimpleLR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QEUauoAsYKYvF16k_0O7_tGRC890PIWO
"""

from math import sqrt
#Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Loading the dataset
dataset = pd.read_csv('drive/MyDrive/ML_Data/gm.csv')
#print(dataset)

#Extracting the independent and dependent variables
X = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

#print(X)
#print(y)

#Dealing with Categorical columns
#Removing the extra dummy variable
#X = pd.get_dummies(X, columns=['City'],drop_first= True)

#Encoding the dependent class variable
#from sklearn.preprocessing import LabelEncoder
#le = LabelEncoder()
#y = le.fit_transform(y)

#print(y)

#Converting to numpy array
X = np.array(X)
y = np.array(y)



#print(X)
#print(y)

#Splitting the data into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)


#Dealing with Missing values
#from sklearn.impute import SimpleImputer
#imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
#X_train[:, [0,1]] = imputer.fit_transform(X_train[:,[0,1]])
#X_test[:, [0,1]] = imputer.transform(X_test[:,[0,1]])


#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#Fitting Linear Regression to Training Set
from sklearn.linear_model import LinearRegression
lrObj = LinearRegression()
lrObj.fit(X_train, y_train)

#Prediction on the Test Set
y_pred = lrObj.predict(X_test)

#We can compare the predicted values with the actual values
print(y_test)
print(y_pred)

#Calculating MSE and RMSE
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print('mean squared error', mse)
print('root mean squared error', sqrt(mse))

#Predicting for a new instance 17.1
scaled_value = scaler.transform([[17.1]])
print(lrObj.predict(scaled_value))

#Visual Exploration of Training Set
plt.scatter(X_train,y_train,color='red')
plt.plot(X_train, lrObj.predict(X_train), color='blue')
plt.title('List Price vs Best Price on Training Set')
plt.xlabel('List Price')
plt.ylabel('Best Price')
plt.show()

#Visual Exploration of Testing Set
plt.scatter(X_test,y_test,color='red')
plt.plot(X_train, lrObj.predict(X_train), color='blue')
plt.title('List Price vs Best Price on Testing Set')
plt.xlabel('List Price')
plt.ylabel('Best Price')
plt.show()

# save the model to disk using Pickle
import pickle
pickle.dump(lrObj, open('lrModel.sav', 'wb'))

# load the model from disk
loaded_model = pickle.load(open('lrModel.sav', 'rb'))
result = loaded_model.predict(X_test)

# save the model to disk using joblib
from joblib import dump, load
dump(lrObj, 'lrModel2.sav')

# load the model from disk
loaded_model = load('lrModel2.sav')
result = loaded_model.predict(X_test)